using AutoMapper;
using Xpress_backend_V2.Models;
using Xpress_backend_V2.Models.DTO;

//public class MappingProfile : Profile
//{
//    public MappingProfile()
//    {

//        //CreateMap<DocumentDTO, PassportDoc>()
//        //       .ForMember(dest => dest.PassportDocId, opt => opt.Ignore()) // Ignore for new entities
//        //       .ForMember(dest => dest.PassportNumber, opt => opt.MapFrom(src => src.PassportNumber))
//        //       .ForMember(dest => dest.IssueDate, opt => opt.MapFrom(src => src.PassportIssueDate))
//        //       .ForMember(dest => dest.ExpiryDate, opt => opt.MapFrom(src => src.PassportExpiryDate))
//        //       .ForMember(dest => dest.IssuingCountry, opt => opt.MapFrom(src => src.IssuingCountry))
//        //       .ForMember(dest => dest.DocumentPath, opt => opt.MapFrom(src => src.DocumentPath))
//        //       .ForMember(dest => dest.UserId, opt => opt.MapFrom(src => src.UserId))
//        //       .ForMember(dest => dest.IsActive, opt => opt.MapFrom(_ => true)) // Default to active
//        //       .ForMember(dest => dest.UploadedAt, opt => opt.MapFrom(_ => DateTime.UtcNow));

//        //CreateMap<PassportDoc, DocumentDTO>()
//        //    .ForMember(dest => dest.PassportNumber, opt => opt.MapFrom(src => src.PassportNumber))
//        //    .ForMember(dest => dest.PassportIssueDate, opt => opt.MapFrom(src => src.IssueDate))
//        //    .ForMember(dest => dest.PassportExpiryDate, opt => opt.MapFrom(src => src.ExpiryDate))
//        //    .ForMember(dest => dest.IssuingCountry, opt => opt.MapFrom(src => src.IssuingCountry))
//        //    .ForMember(dest => dest.IDType, opt => opt.MapFrom(_ => "Passport"));

//        //CreateMap<DocumentDTO, VisaDoc>()
//        //    .ForMember(dest => dest.VisaDocId, opt => opt.Ignore())
//        //    .ForMember(dest => dest.VisaNumber, opt => opt.MapFrom(src => src.VisaNumber))
//        //    .ForMember(dest => dest.IssueDate, opt => opt.MapFrom(src => src.VisaIssueDate))
//        //    .ForMember(dest => dest.ExpiryDate, opt => opt.MapFrom(src => src.VisaExpiryDate))
//        //    .ForMember(dest => dest.VisaClass, opt => opt.MapFrom(src => src.VisaClass))
//        //    .ForMember(dest => dest.DocumentPath, opt => opt.MapFrom(src => src.DocumentPath))
//        //    .ForMember(dest => dest.UserId, opt => opt.MapFrom(src => src.UserId))
//        //    .ForMember(dest => dest.IsActive, opt => opt.MapFrom(_ => true))
//        //    .ForMember(dest => dest.UploadedAt, opt => opt.MapFrom(_ => DateTime.UtcNow));

//        //CreateMap<VisaDoc, DocumentDTO>()
//        //    .ForMember(dest => dest.VisaNumber, opt => opt.MapFrom(src => src.VisaNumber))
//        //    .ForMember(dest => dest.VisaIssueDate, opt => opt.MapFrom(src => src.IssueDate))
//        //    .ForMember(dest => dest.VisaExpiryDate, opt => opt.MapFrom(src => src.ExpiryDate))
//        //    .ForMember(dest => dest.VisaClass, opt => opt.MapFrom(src => src.VisaClass))
//        //    .ForMember(dest => dest.IDType, opt => opt.MapFrom(_ => "Visa"));

//        //CreateMap<DocumentDTO, AadharDoc>()
//        //    .ForMember(dest => dest.AadharId, opt => opt.Ignore())
//        //    .ForMember(dest => dest.AadharNumber, opt => opt.MapFrom(src => src.AadharNumber))
//        //    //.ForMember(dest => dest.FullName, opt => opt.MapFrom(src => src.FullName))
//        //    //.ForMember(dest => dest.DateOfBirth, opt => opt.MapFrom(src => src.DateOfBirth))
//        //    .ForMember(dest => dest.DocumentPath, opt => opt.MapFrom(src => src.DocumentPath))
//        //    .ForMember(dest => dest.UserId, opt => opt.MapFrom(src => src.UserId))
//        //    .ForMember(dest => dest.UploadedAt, opt => opt.MapFrom(_ => DateTime.UtcNow));

//        //CreateMap<AadharDoc, DocumentDTO>()
//        //    .ForMember(dest => dest.AadharNumber, opt => opt.MapFrom(src => src.AadharNumber))
//        //    .ForMember(dest => dest.AadharName, opt => opt.MapFrom(src => src.AadharName))
//        //    .ForMember(dest => dest.IDType, opt => opt.MapFrom(_ => "Aadhar"));

//        CreateMap<DocumentDTO, PassportDoc>()
//                .ForMember(dest => dest.PassportDocId, opt => opt.Ignore()) // PK, generated by DB
//                .ForMember(dest => dest.IsActive, opt => opt.Ignore()); // Set explicitly in repo

//        CreateMap<DocumentDTO, VisaDoc>()
//            .ForMember(dest => dest.VisaDocId, opt => opt.Ignore()) // PK, generated by DB
//            .ForMember(dest => dest.IsActive, opt => opt.Ignore()); // Set explicitly in repo

//        CreateMap<DocumentDTO, AadharDoc>()
//            .ForMember(dest => dest.AadharId, opt => opt.Ignore()); // PK, generated by DB
//                                                                    // Assuming AadharDoc does not have an IsActive property managed this way.
//                                                                    // If it does, add .ForMember(dest => dest.IsActive, opt => opt.Ignore());


//        // --- From Entity to DTO ---
//        // For returning document data. We map the entity's PK to the DTO's Id.
//        // Crucially, we set the IDType string based on the source entity type.

//        CreateMap<PassportDoc, DocumentDTO>()
//            .ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.PassportDocId))
//            .ForMember(dest => dest.IDType, opt => opt.UseValue("Passport"));

//        CreateMap<VisaDoc, DocumentDTO>()
//            .ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.VisaDocId))
//            .ForMember(dest => dest.IDType, opt => opt.UseValue("Visa"));

//        CreateMap<AadharDoc, DocumentDTO>()
//            .ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.AadharId))
//            .ForMember(dest => dest.IDType, opt => opt.UseValue("Aadhar"));
//    }
//}

namespace Xpress_backend_V2.Profiles // Or your appropriate namespace
{
    public class MappingProfile : Profile
    {
        public MappingProfile()
        {
            // --- From DTO to Entity ---
            CreateMap<DocumentDTO, PassportDoc>()
                .ForMember(dest => dest.PassportDocId, opt => opt.Ignore())
                .ForMember(dest => dest.IsActive, opt => opt.Ignore());

            CreateMap<DocumentDTO, VisaDoc>()
                .ForMember(dest => dest.VisaDocId, opt => opt.Ignore())
                .ForMember(dest => dest.IsActive, opt => opt.Ignore());

            CreateMap<DocumentDTO, AadharDoc>()
                .ForMember(dest => dest.AadharId, opt => opt.Ignore());


            // --- From Entity to DTO ---
            CreateMap<PassportDoc, DocumentDTO>()
                .ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.PassportDocId))
                .ForMember(dest => dest.IDType, opt => opt.MapFrom(src => "Passport")); // Changed here

            CreateMap<VisaDoc, DocumentDTO>()
                .ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.VisaDocId))
                .ForMember(dest => dest.IDType, opt => opt.MapFrom(src => "Visa")); // Changed here

            CreateMap<AadharDoc, DocumentDTO>()
                .ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.AadharId))
                .ForMember(dest => dest.IDType, opt => opt.MapFrom(src => "Aadhar")); // Changed here
        }
    }
}